version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sourceme
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      runas: root